// Generated by scripts/generate-demo-audio.mjs.
const clips: Record<string, string> = {
  "GRACE\u0000happy\u0000你好！我是 Grace。": "grace-4e4cda9edd9ee89a27c1.wav",
  "GRACE\u0000neutral\u0000Hello! I am Grace.": "grace-c0e09e802144612caeac.wav",
  "ELLIOTT\u0000happy\u0000我是 Elliott。我们一起玩吧！": "elliott-c6f3c81f37ce460aa69a.wav",
  "ELLIOTT\u0000neutral\u0000I am Elliott. Let's play together!": "elliott-8fb0da46bdb831e802e0.wav",
  "GRACE\u0000happy\u0000玩得开心！": "grace-c72f3e07d5616ff9bbc6.wav",
  "GRACE\u0000neutral\u0000Have fun!": "grace-1b07128a9d3ef15fc18b.wav",
  "GRACE\u0000happy\u0000Elliott, let's build the tallest tower ever!": "grace-903d82c9270d2d3c4f8f.wav",
  "ELLIOTT\u0000surprised\u0000Taller than me?": "elliott-cbf40483c27bfc867314.wav",
  "GRACE\u0000neutral\u0000Much taller than you!": "grace-e42e271122b90ec3520e.wav",
  "ELLIOTT\u0000neutral\u0000Leah found the last block.": "elliott-6839dc920b2473b866b2.wav",
  "GRACE\u0000surprised\u0000The tower is wobbling!": "grace-a33a872b83dabeef3b0d.wav",
  "ELLIOTT\u0000laughing\u0000I guess it was taller than me!": "elliott-8d800f5bbcd102e18f5f.wav",
  "GRACE\u0000happy\u0000Building together is the best part.": "grace-70d100cd5dc9e84a879f.wav",
  "SARAH\u0000surprised\u0000Anna! Why is the storybook glowing?": "sarah-6e08d2ecc100533a1620.wav",
  "ANNA\u0000confused\u0000I don't know. Maybe we should step back...": "anna-a14bbdaf4e15283fa287.wav",
  "SARAH\u0000scared\u0000It's pulling us in!": "sarah-0ab3cc3e87febfab6978.wav",
  "ANNA\u0000scared\u0000Hold my hand, Sarah!": "anna-87e4775f589e1b85a228.wav",
  "SARAH\u0000surprised\u0000Look at all the green hills!": "sarah-e1cf3430d23d473a5c58.wav",
  "ANNA\u0000neutral\u0000That yellow house looks just like Peppa Pig's house!": "anna-2cf7bb18426100296d77.wav",
  "SARAH\u0000happy\u0000We're in Peppa's world! I want to jump in a muddy puddle!": "sarah-3d288efc6b0c6e726fc5.wav",
  "ANNA\u0000confused\u0000Maybe start with a little puddle?": "anna-b1ea6e9ce49a47e37229.wav",
  "ANNA\u0000laughing\u0000This puddle was deeper than it looked!": "anna-d8330d37876d18bc0984.wav",
  "SARAH\u0000surprised\u0000I hear oinking beyond the hill!": "sarah-e2e0fb2c0538dcf0297d.wav",
  "ANNA\u0000happy\u0000Peppa! George! We're coming to say hello!": "anna-e02913b806db2dced41c.wav",
  "SARAH\u0000laughing\u0000Best storybook ever!": "sarah-2dd34018464f392ce147.wav",
  "ANNA\u0000happy\u0000Come on, Sarah! Let's find the flowers.": "anna-df64fbf576dfc04a95a9.wav",
  "SARAH\u0000surprised\u0000Flowers?": "sarah-9df89ef1270af391e91e.wav",
  "ANNA\u0000neutral\u0000Look! One is dancing in the breeze.": "anna-c0c8600c64ece84e28a6.wav",
  "SARAH\u0000laughing\u0000Then we should dance too!": "sarah-059bd87a674725d25fd6.wav",
  "ANNA\u0000happy\u0000Sisters make every adventure better.": "anna-c3169999fe19f41c1143.wav",
  "GRACE\u0000happy\u0000The Treat Spot has ice cream and chips!": "grace-92502c61fe9adb8d9e38.wav",
  "ELLIOTT\u0000confused\u0000But everyone will see us.": "elliott-8409d0a3a0f12b001c09.wav",
  "ANNA\u0000happy\u0000Not if we act like trees.": "anna-6af47785505dac0a125b.wav",
  "ELLIOTT\u0000neutral\u0000They're looking away. Now!": "elliott-765f86637b1448f91695.wav",
  "GRACE\u0000happy\u0000I got the ice cream!": "grace-5a43876babfc81ab363e.wav",
  "ELLIOTT\u0000happy\u0000And I found the chips!": "elliott-c91c549dafed08e13f8b.wav",
  "ANNA\u0000surprised\u0000Quick! They're turning around!": "anna-57b8be5bc3e2c100341e.wav",
  "ANNA\u0000laughing\u0000These are the happiest trees at camp.": "anna-5b20672afe229678a413.wav"
};

export function demoVoiceClipUrl(key: string): string | null {
  const filename = clips[key];
  return filename ? `${import.meta.env.BASE_URL}audio/demos/${filename}` : null;
}
