import { invokeCharacterTts } from '../auth/supabase';
import type { CharacterEmotion } from '../engine/storyTypes';
import { settings } from '../engine/settings';
import { detectSpeechLanguage, hasClonedVoice } from './voicePolicy';
import { demoVoiceClipUrl } from './demoVoiceClips';

export interface SpeechLine {
  character: string;
  text: string;
  emotion?: CharacterEmotion;
}

/** Plays private, authenticated character voices generated by Supabase + Replicate. */
export class Narrator {
  private audio: HTMLAudioElement | null = null;
  private audioCache = new Map<string, Blob>();
  private pendingAudio = new Map<string, Promise<Blob>>();
  private request: AbortController | null = null;
  private finishPlayback: (() => void) | null = null;

  /** Warms unique dialogue lines after a valid story is submitted. */
  prepare(lines: SpeechLine[]): void {
    if (!settings.voices) return;
    const queue = [...new Map(lines
      .filter((line) => hasClonedVoice(line.character))
      .map((line) => [this.keyFor(line), line])).values()]
      .filter((line) => !this.audioCache.has(this.keyFor(line)));

    const worker = async () => {
      while (queue.length > 0) {
        const line = queue.shift();
        if (!line) return;
        try {
          await this.fetchAudio(line);
        } catch {
          // Text-only playback remains available when signed out or TTS is unavailable.
        }
      }
    };
    void Promise.all([worker(), worker()]);
  }

  async speak(line: SpeechLine): Promise<void> {
    this.stop();
    if (!settings.voices || !hasClonedVoice(line.character)) return;

    const request = new AbortController();
    this.request = request;
    try {
      const blob = await this.fetchAudio(line, request.signal);
      if (request.signal.aborted) return;
      const url = URL.createObjectURL(blob);
      const audio = new Audio(url);
      this.audio = audio;
      await new Promise<void>((resolve) => {
        const finish = () => {
          URL.revokeObjectURL(url);
          if (this.audio === audio) this.audio = null;
          if (this.finishPlayback === finish) this.finishPlayback = null;
          resolve();
        };
        this.finishPlayback = finish;
        audio.addEventListener('ended', finish, { once: true });
        audio.addEventListener('error', finish, { once: true });
        void audio.play().catch(finish);
      });
    } catch (error) {
      if (!request.signal.aborted) console.warn('[animate] Character voice unavailable:', error);
    } finally {
      if (this.request === request) this.request = null;
    }
  }

  private keyFor(line: SpeechLine): string {
    return `${line.character.toUpperCase()}\0${line.emotion ?? 'neutral'}\0${line.text}`;
  }

  private fetchAudio(line: SpeechLine, signal?: AbortSignal): Promise<Blob> {
    const key = this.keyFor(line);
    const cached = this.audioCache.get(key);
    if (cached) return Promise.resolve(cached);
    const pending = this.pendingAudio.get(key);
    if (pending) return pending;

    const timeout = AbortSignal.timeout(70_000);
    const combinedSignal = signal ? AbortSignal.any([signal, timeout]) : timeout;
    const demoUrl = demoVoiceClipUrl(key);
    const source = demoUrl
      ? fetch(demoUrl, { signal: combinedSignal }).then((response) => {
          if (!response.ok) throw new Error('Bundled demo voice is unavailable.');
          return response.blob();
        })
      : invokeCharacterTts({
          character: line.character.toUpperCase(),
          text: line.text,
          emotion: line.emotion ?? 'neutral',
          language: detectSpeechLanguage(line.text),
        }, combinedSignal);
    const request = source.then((blob) => {
      this.audioCache.set(key, blob);
      return blob;
    }).finally(() => {
      this.pendingAudio.delete(key);
    });
    this.pendingAudio.set(key, request);
    return request;
  }

  stop(): void {
    this.request?.abort();
    this.request = null;
    if (this.audio) {
      this.audio.pause();
      this.audio.removeAttribute('src');
      this.audio.load();
      this.audio = null;
    }
    this.finishPlayback?.();
    this.finishPlayback = null;
  }
}
